### ISSUE TITLE
Where is the metadata saved ?

### ISSUE THREAD

**Issue by ArieHein** [PowerShellOrg/tug#1]
Do you have a similar location to store the metadata from the nodes signing ?

**Comment by kamranayub** [comment]
It would be great to allow pluggable providers. In my case, it'd be ideal to store in SQL Server since I have a HA pair for my pull servers. The ESENT storage doesn't even work in my testing and had to go back to OLEDB. I'd rather just use SQL since it's a supported technology stack here.

**Comment by concentrateddon** [comment]
At the moment, metadata isn't saved anywhere. The entire *intent* is to allow plugins. Specifically, every pull server request is ultimately served by a PowerShell command you write. So you can do whatever you want with the data. This is *not* the Microsoft pull server and it doesn't imply or specify the use of any particular database.
