### ISSUE TITLE
Question: How to build with the Ps5 provider

### ISSUE THREAD

**Issue by erwinwildenburg** [PowerShellOrg/tug#10]
If I change the singleton in Startup.cs to use Ps5DscHandlerProvider I get the following error:
`The type or namespace name 'Ps5DscHandlerProvider' does not exist in the namespace 'Tug.Server.Providers' (are you missing an assembly reference?)`

Can't we make this more dynamic or do we have to change the project references for each new provider we create?
![error](https://cloud.githubusercontent.com/assets/3199611/20984537/f6d110ee-bcc0-11e6-8271-18e96e42169f.PNG)

**Comment by ebekker** [comment]
The project is not yet setup to support this -- I was working on restructuring the project orgs to support this, and that was just completed with a PR in the last couple of days.  I'll have support for building and running with the Ps5 (and other providers) soon.

**Comment by ebekker** [comment]
I've just committed some changes that allow you to build and try out the PS5 Handler.

It's very basic and just shows example of going *end-to-end* through DSCPS protocol through to PS backend and back, but it's a start.

If you pull the code down and build Tug.Server and the Ps5DscHandler projects, you can invoke `tug.cmd` from the [`test/run-net452`](https://github.com/PowerShellOrg/tug/tree/master/test/run-net452) directory.  This will launch the server with the PS5 Handler enabled.

After initialization, it will start accepting connections (on localhost:5000 by default, no HTTPS) and will be able to respond to all the DSCPS messages, passing them back to a PS context.

It includes a very [basic set of PS cmdlets](https://github.com/PowerShellOrg/tug/blob/master/test/run-net452/DummyTugCmdlets.ps1) to handle each of these messages that do nothing but print statements at this point, but it's a start...

The default handler ([`(https://github.com/PowerShellOrg/tug/blob/master/src/Tug.Server/Providers/BasicDscHandler.cs)) actually has a very minimum, working configuration, that is it supports registrations, action status, getting configurations and getting modules, so my next step is to work on feature parity with the PS5 handler.

But to get there, I'll be doing some major refactoring and cleaning up of the provider model, so it might be a little while stilll...

**Comment by erwinwildenburg** [comment]
I see, I actually already started modifying the code to fit my needs.
I already have working Azure (Storage Tables, Storage Blobs, SQL) implementation complete and working. Which should be maybe 70% compatible with this version.
I will port it as soon as the changes you make settle down to a more stable form ;)

I was just curious how you would implement loading the providers dynamically. I'm just started programming a year ago so I'm actually learning alot by looking at the commits you make.

**Comment by ebekker** [comment]
Great!  Hopefully you don't learn any bad habits from me :-)

The provider model and dynamic loading will be based on similar functionality that I've used before in [another project](https://github.com/ebekker/ACMESharp) and I've been very satisfied with how well it worked out there.  That project is .NET Framework-based but I've already started on a [.NET Core version](https://github.com/PKISharp/core/tree/master/main/src/ACMESharp/Ext) and that is what I'll start with for tug.  I'll pby make some simplifications and adjustments to make it work well with DI and other concerns.

Under the hood, the provider model is based on MEF 2.

**Comment by ebekker** [comment]
@erwinwildenburg, I just committed a large PR that includes what I believe to be the final set of abstractions and implementations of support for the provider model.  This includes dynamic provider discovery and loading (check out `Tug.Ext.Util.ProviderManagerBase#FindProviders` in the `Tug.Base` assembly for the secret ingredient).

You should be able to build all the projects and then from the `/test/run-net452` folder you can invoke `tug.cmd` to see the server load up the PS5 handler dynamically.

You can see that none of the Tug.Server or related components explicitly reference the PS5 Handler assembly as a dependency, but the `appsettings.json` configuration file provides settings that tell the server where it can find additional provider assemblies and which one to load up and use, specifically with these settings:
* `appSettings:handler:ext:searchPaths`
* `appSettings:handler:provider`

**Comment by ebekker** [comment]
Let me know if you have any problems building/running with these changes.  If not, I think that addresses your original concerns with this ticket.

**Comment by erwinwildenburg** [comment]
@ebekker I will give it a test after I finish playing with unit and integration tests.

**Comment by ebekker** [comment]
@erwinwildenburg -- were you able to confirm, the project builds and runs for you successfully?

**Comment by erwinwildenburg** [comment]
@ebekker yes, I can confirm it works. I didn't have time to figure out how it works yet. Holidays you know ;)
