### ISSUE TITLE
Introduce an extensible Provider model

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#12]
In order to allow flexible back-end implementations of various components, across different environments (e.g. .NET Standard, .NET Core, PowerShell-backed, etc.), we would like to introduce a Provider framework that can be used by various parts of the system.

The first areas that could benefit from this approach include:
* Checksum Algorithms -- the DSCPS spec allows for different checksum algorithms (although the spec and all current implementations only make use of one `SHA-256`)
* Authentication -- there are already several different flavors available in *the wild* include, Node ID, Registration Key and Client Certificate.
* DSC Handler -- the back-end piece that implements DSCPS logic beyond the wire-protocol exchange

**Comment by ebekker** [comment]
@concentrateddon, I've just merged in a large PR that finalizes the provider model, including dynamic discovery and loading of various back-end providers.

There is a basic framework for a PowerShell v5 *DSC Handler* in place.  It doesn't do anything now but print out messages through some dummy PS5 cmdlets.

You can give it a try by pulling and building all the latest changes, and then you can run it from the `/test/run-net452` folder by running the `tug.cmd` file.  This folder defines the configuration settings for discovering and running the PS5 handler.  You will also see the dummy cmdlets in the `DummyTugCmdlets.ps` script in this folder.

**Comment by ebekker** [comment]
Let me know if you have any problems, or any other feedback.

At this point I'm going to leave the PS5 handler up for you to start playing around with as you see fit, and I'll be focusing on other areas, like the authentication layer, finishing up the reporting controller and adding in some much needed unit testing.

**Comment by concentrateddon** [comment]
On it. I'm going to try and spend some time this weekend doing that - it looks great.

**Comment by ebekker** [comment]
The model is in place and I think is working out well in general.

There are some *issues* with dynamic assembly loading in the .NET Core variations under some circumstances, but that could be my own lack of understanding of the proper use of `AssemblyLoadContext` -- I'll need to do a little more research.  (These issues might go away anyway with the expansion of AppDomain and dynamic assembly loading support in future .NET Standard 2.0, but that is still not expected till spring '17.)

I've added out a bunch of unit test code to exercise the model and it's features.
