### ISSUE TITLE
Figure out the proper way to assemble all node IP Addresses for Tug Client

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#26]
Tug Client needs to assemble all of the local host's IP Addresses to send along in initial registration and subsequent reports.

The current implementation as defined in [Program.ComputeAgentInformation()](https://github.com/PowerShellOrg/tug/blob/8463546bf4cfb6db4b4875f176da1c05c1ebbd28/src/Tug.Client/Program.cs#L69) is not right, need to figure out the right formula for doing this on .NET Standard as well as .NET Framework.

**Comment by kamranayub** [comment]
I wonder if you switched from `DnsAddresses` to `UnicastAddresses` if it would work? As shown in this [SO post](http://stackoverflow.com/a/18283999/109458):

```
List<IPAddress> ipList = new List<IPAddress>();
foreach (var ni in NetworkInterface.GetAllNetworkInterfaces()) {
    foreach (var ua in ni.GetIPProperties().UnicastAddresses) {
        if (ua.Address.AddressFamily == AddressFamily.InterNetwork) {
            Console.WriteLine("found ip " + ua.Address.ToString());
            ipList.Add(ua.Address);
        }
    }
}
```

**Comment by ebekker** [comment]
Hi @kamranayub -- that is definitely producing better results than what I had before.  I'm going to switch to using that for now, and we'll see if that's the correct final solution, thanks!

**Comment by ebekker** [comment]
After adding the IPv6 address family (`InterNetworkV6`) and doing some testing and comparison with what the class LCM is sending, this looks to be the correction solution, so I'm going to consider this done.

Thanks @kamranayub!
