### ISSUE TITLE
Where does the authentication logic around `x-ms-date` come from

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#4]
@concentrateddon -- I was reviewing your logic for the Node registration code and I was wondering where you got the logic involving the HMAC hashing and the `x-ms-date` request header?

I didn't see any reference to it in the [specification](https://msdn.microsoft.com/en-us/library/mt590247.aspx) description for the `RegisterDscAgent` operation.

Was this something that you observed/deduced by capturing network traffic?

**Comment by concentrateddon** [comment]
I reverse-engineered it from the Linux LCM.

**Comment by concentrateddon** [comment]
Well, and a bunch of Wireshark traces.

**Comment by ebekker** [comment]
I think I did just find a cursory reference to it in [Section 2.2.2.7](https://msdn.microsoft.com/en-us/library/mt590240.aspx#Appendix_A_Target_4) -- the appendix also mentions that this is only something supported in Win10/Server2016.

**Comment by concentrateddon** [comment]
Nope, it's in all v5 clients. The spec is less-than-100% correct in a few areas.

**Comment by ebekker** [comment]
So the Registration Key is not something that's generated and passed back from server to client during the `RegisterDscAgent` process, so it's expected that a client will be pre-configured with it in advance.

Is it safe to skip this authorization step initially -- in other words, have you found that DSC clients won't work unless they have this shared key to start with?

**Comment by concentrateddon** [comment]
It's a shared secret, yes, so that is the assumption. 

The registration is an HTTP PUT action; so long as you respond OK (vs an error), the client assumes registration was successful. In theory, you could ignore the RegistrationKey and just use something odor-based. Or whatever.

**Comment by ebekker** [comment]
Thanks, that answers my question.

**Comment by ebekker** [comment]
I'm going to suggest moving that authorization logic that you have defined in that part of the current code to a ASP.NET `Filter` which will be accessed across all the DSC operations and will decouple that cross-cutting concern from each operations-specific logic.

**Comment by concentrateddon** [comment]
Yeah, so, that might be a logistical problem. First, the authorization isn't transmitted in every request packet - it's only in a specific Register operation. Second, while the observed behavior is to send that Register before any other request, the _documented_ behavior is to stop sending Register once the node is registered. Third, not every pull server is going to want to rely on that information for registration. Some companies may pre-stage client certificates, for example. 

I think Register needs to continue to be a discrete operation, and passed off to be handled in whatever way the customer wants to handle it - including ignoring it.

**Comment by ebekker** [comment]
I wasn't referring to the Registration operation as a whole -- just the Authorization piece which is a pre-cursor to successful registration.  Maybe this another case of the spec being incorrect, but there was a note in there that the `Authorization` header is supposed to be transmitted with all v2 operations.

I agree about the part about not relying on the pre-shared registration key as the exclusive authorization method -- client-certs or perhaps something completely different (Windows Authentication?) are other options.  That's why I was thinking externalizing that in the [request pipeline](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#how-do-filters-work) and providing a mechanism to *plugin* something.

**Comment by concentrateddon** [comment]
The Authorization can be ignored in a lot of implementations. Azure DSC does, for example. And honestly the native pull server ignores it, too, and relies on the AgentID once the agent is registered. Azure DSC uses the Register operation, gets the client certificate from that, and uses that from then on. I'm a little hesitant to re-engineer what's more or less already been engineered in code we can't touch, yet.
