### ISSUE TITLE
Need to add support for RegKey Authorization

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#41]
To provide the same baseline functionality as the class DSC Pull Server (v2), we need to support authorization by use of [Registration Keys](https://github.com/PowerShellOrg/tug/blob/master/references/regkey-authorization.md) (RegKey Authz).

**Comment by ebekker** [comment]
My intention was initially to make use of the native facilities in ASP.NET Core MVC, such as [Authorization Filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#authorization-filters) and [Action Filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#action-filters), or possibly a custom [Authentication scheme](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme).

However, as I started to explore this further, one of the down sides to this approach is that the RegKey Authz is actually tied to the specific DSC Pull Mode protocol messages, for example it expects one type of authentication data for the `RegDscAgent` message, and then a different element of data for all subsequent messages.

And these elements are typically embedded within the route or message structure which is already being parsed out into a model class for each action method, so we would need to parse this data twice -- once for the filter or authentication scheme handler, and then again for the controller-action model.

**Comment by thedevopsmachine** [comment]
You could add a middleware component that does an "if uri == /Register" (or whatever) then do one form of auth, otherwise do the other. If it succeeds, pass it to the next layer in the stack, otherwise 403. Then your controller code can assume all requests are auth'd, making your unit testing easier since attributes can't utilize dependency injection.

@ebekker can you please update your profile to include your email address? I would like to contact you in private.

**Comment by ebekker** [comment]
I'm exploring something along those lines, not actually path testing, since that can change if you decide to host Tug under a prefix, but by evaluating against a Route Name or an Action Name.  However, that's not the difficult part.  The really sticky part is the double parsing I mentioned, however I think I might be on to an idea that offers the best of both worlds....stay tuned...

You can DM [me](https://powershell.slack.com/team/ebekker) on the PowerShell slack team, which you can sign up for [here](http://slack.poshcode.org/).

**Comment by majst32** [comment]
Is there any part of this that the PS5 handler should handle?  I got to playing with this today and realized (a) that we're not currently doing anything with the reg key and (b) there's nothing in the request body details to use to check against a reg key... which led me to this thread!

**Comment by ebekker** [comment]
@majst32, not exactly -- the authorization piece is handled as a separate concern apart from the core DSC Pull messages.  The idea is to decouple them so that you can swap out different authorization stratetgies, for example PKI client certs or something else entirely (OpenID Connect or AD/Kerberos for example).

So the PS5 Handler is just responsible for the DSC messages.  The RegKey authorization support should be completed soon, I wanted to make sure that it was compatible in behavior with the classic DSC Pull Service.

**Comment by ebekker** [comment]
RegKey Authz has been implemented in the form of an ASP.NET MVC Filter.

**Comment by ebekker** [comment]
@majst32, I've updated the PS5 test run config to incorporate support for this, so now RegKey authorization is in place.

You'll see there were a couple edits in the `BasicTugCmdlets.ps1` file to remove the use of an unnecessary parameter now, and the `appsettings.json` file has been updated to add some additional config for the filter to work correctly.
