### ISSUE TITLE
Move to ASP.NET MVC controllers and models

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#5]
I suggest moving to make use of ASP.NET Core's MVC framework which uses controllers and models to cleanly structure the code base in terms of functional areas, action methods and declarative request model binding.

@concentrateddon, I have a working version of this approach in a [separate branch](https://github.com/zyborg/tug/tree/move-to-mvc).  I would like to discuss this approach and review the code base.  We can start the discussion by looking at the [main controller](https://github.com/zyborg/tug/blob/move-to-mvc/src/tug/Controllers/DscController.cs) and the supporting [model classes](https://github.com/zyborg/tug/tree/move-to-mvc/src/tug/Messages).

**Comment by concentrateddon** [comment]
I'm out for a couple of weeks, but will definitely get started on having a look as soon as possible.

**Comment by concentrateddon** [comment]
I'll also mention that it needs to, at present, target full ASP.NET, not Core; after some additional testing and help from the PowerShell team, calling PowerShell in Core just isn't going to perform at this stage. I realize the syntax shouldn't need to change, but it does need to target the full CLR.

**Comment by ebekker** [comment]
Yep, I'm running it on .NET Standard right now, so that's not an issue.

**Comment by ebekker** [comment]
I've started to document the observed but undocumented behavior of the default LCM client + xDscWebService pull server.  That document is [here](https://github.com/zyborg/tug/blob/move-to-mvc/references/observations.md) in that MVC branch.

You mentioned you deciphered some of the operational behavior just by doing network traces, so if you want to capture and document any of your findings, feel free to update the doc.

**Comment by concentrateddon** [comment]
So overall, I'm fine with that approach if you're going to stick with it and help me get it done ;). I'm no ASP.NET expert; I'm a PowerShell guy! If you'd like, we can merge the branch in and make that the mainline project. If you get a provider model in place, I'd like to (personally) start with a PowerShell Command provider - e.g., running specific commands in response to LCM requests. That's the big underserved market right now, and would let PowerShell people start customizing their own pull servers. In full .NET, it's basically a couple lines of code to instantiate PowerShell and run a command, so not a big hurdle (hopefully).

**Comment by ebekker** [comment]
You read my mind -- I just started the skeleton of the PS5 handler, which I just committed [here](https://github.com/zyborg/tug/tree/move-to-mvc/src/Tug.Server.Providers.Ps5Handler).

One thing that I wanted to do some research on (from PS team or SME's like yourself) -- is the [PS API for hosting](https://msdn.microsoft.com/en-us/library/system.management.automation.powershell%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#) geared to support mutli-threaded access?

The MSDN docs seem to indicate not, so if that's the case the only way to safely power tug with callouts to POSH is to synchronize all calls, which would have a big performane/scalability impact, or alternatively so start pooling POSH contexts (runspaces) much like DB connections.

So I think this will be one of the first things to tackle in the PS5 implementation once a basic working structure is in place.

**Comment by ebekker** [comment]
Oh, and to address your concern -- yes, I full intend to *stick with it* -- tug actually addresses an itch I've been wanting to scratch for almost a year myself, so I'm quite motivated to see it through.

**Comment by ebekker** [comment]
I had submitted a PR (#3) a few days ago that re-organized the project structure a bit, that was a precursor to the MVC migration work I'm doing in that other branch.  If you can approve the PR, then I can submit the MVC work and the provider model work in a subsequent PR.

**Comment by concentrateddon** [comment]
I _cannot_ get GitHub to reliably notify me when there's a PR. Annoying. Anyway, I've added you as a collaborator; you should have push access, now. 

System.Management.Automation alleges to be thread-safe, and I've used it in some fairly high-scale applications before. It's designed to be used in ASP.NET this way, so it should be fine. PowerShell itself runs multithreaded just fine in its Jobs feature, which is essentially the same thing. If we start talking about 1,000s of simultaneous requests it might get a bit boggy, but there are workarounds for that - including pooling contexts as you suggest. But it's also just as easy to spin up new web servers, w which is what a lot of us want to do anyway - the current pull server can't be made highly available, which multiple web servers obviously gets you.

**Comment by concentrateddon** [comment]
BTW, I'm not going to be able to get to the repo for much of this week, so do feel free to push.

**Comment by ebekker** [comment]
Thanks! (for the info and the access)

**Comment by kamranayub** [comment]
Watching this intently--as soon as tug can allow me to write SQL/EF integration and expose better reporting endpoints, I'll jump in with a provider 💯

**Comment by ebekker** [comment]
I've completed the migration to ASP.NET MVC and merged all the changes back in, so I'm going to close this ticket out.
