### ISSUE TITLE
Issue with registration and Authz

### ISSUE THREAD

**Issue by majst32** [PowerShellOrg/tug#50]
I pulled all the latest code with the Authz changes in it, but I am unable to get my target node to register, or re-register, or even enter the PS5 handler.  I restructured the _IGNORE folder to be _IGNORE\DscService\Authz and _IGNORE\DscService\Authz\Registrations and the registrationKeys.txt is in the  _IGNORE\DscService\Authz folder.  AppSettings.json have been updated with "RegistrationSavePath": "_IGNORE/DscService/Authz/Registrations".  

Still Tug insists it cannot find the registrationKeys.txt:  

2017-01-16 08:38:11.2564|0|DEBUG|Tug.Server.Filters.DscRegKeyAuthzFilter|resolved reg key file path as [C:\Users\administrator\Documents\GitHub\tug\test
\run-net452-ps5\_IGNORE\DscService\Authz\RegistrationKeys.txt] 

2017-01-16 08:38:11.3314|0|DEBUG|Tug.Server.Filters.DscRegKeyAuthzFilter|resolved reg save path as [C:\Users\administrator\Documents\GitHub\tug\test\run
-net452-ps5\_IGNORE\DscService\Authz\Registrations] 

2017-01-16 08:38:11.3314|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HL1U4MMKK2O9": An unhandled exception was thrown by the applicatio
n. System.InvalidOperationException: could not find registration key file at Tug.Server.Filters.DscRegKeyAuthzFilter..ctor(ILogger`1 logger, IOptions`1 settings)

**Comment by ebekker** [comment]
That's strange, it's resolving the full path to the keys as:
```
C:\Users\administrator\Documents\GitHub\tug\test
\run-net452-ps5_IGNORE\DscService\Authz\RegistrationKeys.txt
```

You'll note there isn't a `\` in between the `run-net-452` and the `_IGNORE`.  Try putting a backslash just before the _IGNORE in the appsettings.json file and see if that fixes your issue.  If it does, we'll need to figure out why it's resolving differently on different machines (maybe a .NET Framework difference of some kind).

**Comment by majst32** [comment]
I see the \ between ps5 and \_IGNORE on my screen in the output.  That may have been a cut-and-paste issue.  I did try adding a / before _IGNORE in appsettings.json and it interpreted it as C:\_IGNORE...

Nonetheless, I'm still getting the error that it can't find the registration file.  (And now the output path looks ok copied and pasted).  And it exists in C:\Users\administrator\Documents\GitHub\tug\test\run-net452-ps5\_IGNORE\DscService\Authz\RegistrationKeys.txt

2017-01-16 09:33:45.8555|1|DEBUG|Microsoft.AspNetCore.Routing.Tree.TreeRouter|Request successfully matched the route with name 'RegisterDscAgentRequest'
 and template 'Nodes(AgentId='{AgentId}')'. 

2017-01-16 09:33:45.9795|0|DEBUG|Tug.Server.Filters.DscRegKeyAuthzFilter|resolved reg key file path as [C:\Users\administrator\Documents\GitHub\tug\test
\run-net452-ps5\_IGNORE\DscService\Authz\RegistrationKeys.txt] 

2017-01-16 09:33:46.0715|0|DEBUG|Tug.Server.Filters.DscRegKeyAuthzFilter|resolved reg save path as [C:\Users\administrator\Documents\GitHub\tug\test\run
-net452-ps5\_IGNORE\DscService\Authz\Registrations] 

2017-01-16 09:33:46.0715|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HL1U5LODMC69": An unhandled exception was thrown by the applicatio
n. System.InvalidOperationException: could not find registration key file
   at Tug.Server.Filters.DscRegKeyAuthzFilter..ctor(ILogger`1 logger, IOptions`1 settings)

**Comment by majst32** [comment]
The missing \ is a lie.  I think it is a formatting issue on this forum.

**Comment by ebekker** [comment]
looks like `\_` is actually an escape sequence in Markdown that just produces the `_` character -- you have to either double-up on the backslash as in `\\_` which produces **\\_** or put things like line paths in inline code fragments using back ticks (\`) as in `this\is\a\path\with\an\_IGNORE`.

**Comment by ebekker** [comment]
So getting back to your original issue -- I tired a number of variations but the only way that I could produce your error is if I forced and incorrect path in the appsettings file or removed/renamed the RegKey file.

Is the path and file within readable by the user account that's running the tug.cmd process?  (I assume you're just running it as yourself.)

**Comment by majst32** [comment]
The file is read- and writable by the user I am logged on with (Administrator) as is also the same userid I am running Tug under.  The registrationKeys.txt file is under the RegistrationKeyPath.

"authz": {
            "params": {
                // This is where we look for the file containing reg keys,
                // which is named "RegistrationKeys.txt" by default.  In this
                // file we look for non-blank lines after removing any comments
                // starting with the '#' character and trimming from both ends
                "RegistrationKeyPath": "_IGNORE/DscService/Authz",
                // We keep our own copy of registrations that is separate from
                // those saved by the Pull Handler down below which is strictly
                // for authz purposes -- these may overlap but could cause conflicts
                "RegistrationSavePath": "_IGNORE/DscService/Authz/Registrations"
            }
...
// // For testing purposes, we redefine these to make sure they get
                // // placed under the _IGNORE subfolder so they are ignored by Git
                "RegistrationSavePath": "_IGNORE/DscService/Authz/Registrations",
                "ConfigurationPath": "_IGNORE/DscService/Configuration",
                "ModulePath": "_IGNORE/DscService/Modules"

Still with same error.  :(

**Comment by majst32** [comment]
Any ideas?  We could Skype if you want to troubleshoot, or I can rebuild the tug server again.  What do you think is my best option?  I'm stuck.

**Comment by ebekker** [comment]
Missy, I'm wondering if we can try another route and knock out two birds, if you're up to it.

I wanted to put together a couple *pre-configured bundles* of Tug that included several of the available components as well as starting configuration files and working samples in order to get someone up and running quickly, especially if they're not a developer and just want to be able to use the thing.

The first bundle I've put together is the Tug Server coupled with the PS5 back-end handler and the RegKey authorization support, along with the latest Basic PS script that you updated last week.  I've tested it out in a few configurations myself, but I wanted to have a few others test it out before I made it official and broadcasted it out.

So if you're up to it, this would be a way for you to test it out and make sure it works for you, *and* this would also get you past this problem you're running into, as it would get you to the point where you have a running Tug Server with PS5 and the RegKey support.

**Comment by ebekker** [comment]
If you're game, here's how to go about installing with it.  Right now, I have the bundle published to a *pre-release* Nuget feed, if testing proves it's successful, then I'll publish it to the PowerShell Gallery.

## Step 1:  Register the Pre-release Tug Nuget Feed
```PowerShell
PS> Register-PSRepository -Name tug-pre -SourceLocation https://www.myget.org/F/tug/api/v2 -PackageManagementProvider nuget -Verbose

## You can list all the available modules in the Pre-release feed
PS> Find-Module -Repository tug-pre
```

## Step 2:  Install the PowerShell Module containing the Pre-Configured Bundle
```PowerShell
PS> Install-Module -Repository tug-pre Tug.Server-ps5
```

## Step 3:  Install the Tug Server Bundle
```PowerShell
PS> Import-Module Tug.Server-ps5
PS> Install-TugServer
```

The `Install-TugServer` cmdlet takes a parameter to override the default installation path, which is `%PROGRAMFILES%\Tug\Server`.

## Step 4:  README, Final Configuration and Running
In the installation directory, you'll find a `README.md` file that will give an overview of what the bundle contains, what options you can tweak and where to get more info.  **I would love your feedback on this to make sure it's clear for someone to start with.**  I know it's not complete, but I think it's in a good condition to start with.

Using the README, you can adjust the final settings and then you can launch the server in an interactive console from CMD or PowerShell:
```
> cd <install-directory>
> .\tug-server.cmd
```

**Comment by majst32** [comment]
Sounds like a plan!  I will save off some stuff and start rebuilding.

**Comment by majst32** [comment]
The install instructions are fantastic.  It was easy to install and uses familiar commands.  And I was able to register my node!  Couple questions: 
(1) Do you want to include the firewall configuration command?  New-NetFirewallRule -name "Tug Inbound" -Enabled true -DisplayName "Tug inbound" -Direction Inbound -RemoteAddress any -Protocol tcp -LocalPort 5000
(2) In the readme, it states that the configname.mof file needs to be located in a /SHARED folder under Configurations.  Why?  This seems odd and I don't believe it was needed for the Microsoft pull server.
(3) In which folder should I make changes?  tug/src/... or tug/test/.... ?

**Comment by ebekker** [comment]
Thanks for the great feedback.

(3) The files that make up the bundle are under the src subtree located [here](https://github.com/PowerShellOrg/tug/tree/master/src/bundles/Tug.Server-ps5).

(2) That is correct, initially I have this SHARED folder structure to distinguish it from node-specific configs (i.e. the shift from Node IDs (v1) to Node Names + Reg Keys (v2)).  But likely we'll only support v2 variations out of the box, so we can pby do away with the SHARED business.  This path calculation is actually done in the `BasicTugCmdlets.ps1` sample script so that can be quickly adjusted and the README as well to match.

(1) That's a good point -- we can put that as default behavior into the Install cmdlet, maybe with a "switch" to override/disable it if the user wants to.

**Comment by majst32** [comment]
This issue is fixed... should I close it?

**Comment by ebekker** [comment]
Yes you can close it once your issue is addressed, I'll close this one this time.

**Comment by ebekker** [comment]
@majst32, FYI I've moved the deployment instructions in this ticket out to [this wiki page](https://github.com/PowerShellOrg/tug/wiki/HOWTO:--Deploy-Prerelease-Tug-Server-&-PS5-Bundle) and made some changes/enhancements along the way.  I'll maintain the wiki page in sync with any future changes to the install/update process of the prerelease NuGet feed.
