### ISSUE TITLE
Add support for *file-watching* and *reloading*

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/tug#60]
During development and testing of PowerShell script(s) that are driving the behavior of the PS5 Handler, it would be useful to have the handler watch for changes to certain files, such as the PS script files and automatically reload the PowerShell Runspace with the newest changes.

Right now, it's necessary to stop and start the server manually to pickup any changes.

**Comment by majst32** [comment]
Agreed.  Also @theJasonHelmick  pointed out that once Tug is started up it should return control of the ISE/powershell console to the user and continue running in the background.

**Comment by ebekker** [comment]
Because of the way that ASP.NET Core operates (it's essentially a console application that hosts its own Web server (Kestrel)) the way to fix that is to deploy it so that it's fronted by IIS.

I'll add into the `Install-TugServer` installation logic shortly.

**Comment by ebekker** [comment]
I've moved Jason's request to #65.
